#!/bin/bash

deepspeed transfusion/train/train.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path data/liuhaotian/LLaVA-Instruct-150K/llava_v1_5_mix665k_filtered.json \
    --image_folder data/liuhaotian/LLaVA-Instruct-150K/data \
    --vision_tower lavinal712/transfusion-vae \
    --mm_projector_type linear_2 \
    --gen_projector_type linear_2 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --mm_use_im_patch_token False \
    --mm_input_size 32 \
    --mm_patch_size 2 \
    --mm_in_channels 8 \
    --mm_out_channels 16 \
    --image_aspect_ratio fix \
    --mm_image_size 256 \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/transfusion-7b-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --max_grad_norm 1.0 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
